/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas.libro;

import DAOs.EjemplarDAO;
import vistas.estudiantes.*;
import DAOs.EstudianteDAO;
import DAOs.LibroDAO;
import DAOs.TemaDAO;
import entidades.Estudiante;
import entidades.Libro;
import entidades.Tema;
import excepcionesPropias.ExcepcionPropia;
import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import listasPropias.ListaLibros;
import listasPropias.ListaTemas;
import vistas.tema.GUIRegistroTema;
import vistas.principal.GUIPrincipal;

/**
 *
 * @author Alexander
 */
public class GUIAgregarNuevoEjemplar extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUIAgregarNuevoEjemplar
     */
    
    LibroDAO libroDAO = new LibroDAO();
    EjemplarDAO ejemplarDAO = new EjemplarDAO();
    ArrayList<Libro> listaLibros;
    
    public GUIAgregarNuevoEjemplar() {
        initComponents();
        configurarEncabezadoJTable();
        llenarJTableLibros();
    }

    private void limpiar(){
        txtBusquedaTitulo.setText("");
        txtTitulo.setText("");
        txtAutor.setText("");
        txtIsbn.setText("");
        txtAnio.setText("");
        txtTema.setText("");
    }
    
    private void establecerPorDefecto(){
        limpiar();
        llenarJTableLibros();
    }
    
    private void configurarEncabezadoJTable(){
        jTableLibros.getTableHeader().setFont(new Font("Verdana", Font.BOLD, 14));
        jTableLibros.getTableHeader().setOpaque(false);
        jTableLibros.getTableHeader().setForeground(Color.BLACK);
        
    }
    
    private void llenarJTableLibros(){
        DefaultTableModel dtm = new DefaultTableModel();
        
        listaLibros = new ArrayList<>();
        
        try {
            listaLibros = libroDAO.obtenerLibros();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Hubo un problema al cargar los datos de libros.");
        }
        
        String[] cabecera = {"Código", "ISBN", "Título", "Autor", "Tema", "Año", "Idioma"}; 
        dtm.setColumnIdentifiers(cabecera);
        dtm.setColumnCount(cabecera.length);
        Object[] dataLibros = new Object[dtm.getColumnCount()];
        
        for (int i = 0; i < listaLibros.size(); i++) {
            dataLibros[0] = listaLibros.get(i).getId();
            dataLibros[1] = listaLibros.get(i).getIsbn();
            dataLibros[2] = listaLibros.get(i).getTitulo();
            dataLibros[3] = listaLibros.get(i).getAutores();
            dataLibros[4] = listaLibros.get(i).getTema().getDescripcion();
            dataLibros[5] = listaLibros.get(i).getAniopublicacion();
            dataLibros[6] = listaLibros.get(i).getIdioma().getDescripcion();
            dtm.addRow(dataLibros);
        }
        jTableLibros.setModel(dtm);
    }
    
    private void llenarJTableLibros(ArrayList<Libro> libros){
        
        DefaultTableModel dtm = new DefaultTableModel();
        
        String[] cabecera = {"Código", "ISBN", "Título", "Autor", "Tema", "Año", "Idioma"}; 
        dtm.setColumnIdentifiers(cabecera);
        dtm.setColumnCount(cabecera.length);
        Object[] dataLibros = new Object[dtm.getColumnCount()];
        
        for (int i = 0; i < libros.size(); i++) {
            dataLibros[0] = listaLibros.get(i).getId();
            dataLibros[1] = listaLibros.get(i).getIsbn();
            dataLibros[2] = listaLibros.get(i).getTitulo();
            dataLibros[3] = listaLibros.get(i).getAutores();
            dataLibros[4] = listaLibros.get(i).getTema().getDescripcion();
            dataLibros[5] = listaLibros.get(i).getAniopublicacion();
            dataLibros[6] = listaLibros.get(i).getIdioma().getDescripcion();
            dtm.addRow(dataLibros);
        }
        jTableLibros.setModel(dtm);
    }
    
    public void irAGUILibro(){
        GUIPrincipal.vacearDktpPane();
        
        GUILibro guiLibro = new GUILibro();
        GUIPrincipal.agregarJframe(guiLibro);
        guiLibro.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpOrdenamiento = new javax.swing.ButtonGroup();
        jPaneEstudiante = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        txtBusquedaTitulo = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableLibros = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIsbn = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtAutor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtTema = new javax.swing.JTextField();
        btnGenerarEjemplar = new javax.swing.JButton();
        txtAnio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtIdioma = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(900, 530));

        jPaneEstudiante.setPreferredSize(new java.awt.Dimension(900, 530));
        jPaneEstudiante.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        jLabel31.setText("Buscar título:");
        jPaneEstudiante.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        txtBusquedaTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBusquedaTituloKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaTituloKeyReleased(evt);
            }
        });
        jPaneEstudiante.add(txtBusquedaTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 420, -1));

        jTableLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableLibros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLibrosMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTableLibros);

        jPaneEstudiante.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 600, 420));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Nuevo ejemplar de libro");
        jPaneEstudiante.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("ISBN");
        jPaneEstudiante.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        txtIsbn.setEditable(false);
        jPaneEstudiante.add(txtIsbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 250, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Título");
        jPaneEstudiante.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        txtTitulo.setEditable(false);
        jPaneEstudiante.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 250, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Autor");
        jPaneEstudiante.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        txtAutor.setEditable(false);
        jPaneEstudiante.add(txtAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 250, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Tema:");
        jPaneEstudiante.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
        });
        jPaneEstudiante.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 130, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Año de publicación");
        jPaneEstudiante.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        txtTema.setEditable(false);
        jPaneEstudiante.add(txtTema, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 250, -1));

        btnGenerarEjemplar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGenerarEjemplar.setText("Generar nuevo ejemplar");
        btnGenerarEjemplar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGenerarEjemplarMouseClicked(evt);
            }
        });
        jPaneEstudiante.add(btnGenerarEjemplar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 240, 40));

        txtAnio.setEditable(false);
        jPaneEstudiante.add(txtAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 250, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Código");
        jPaneEstudiante.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        txtCodigo.setEditable(false);
        jPaneEstudiante.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 250, -1));

        txtIdioma.setEditable(false);
        jPaneEstudiante.add(txtIdioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 250, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Idioma");
        jPaneEstudiante.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBusquedaTituloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaTituloKeyReleased
        
    }//GEN-LAST:event_txtBusquedaTituloKeyReleased

    private void jTableLibrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLibrosMouseClicked
        int filaSeleccionada = 0;
        
        if(jTableLibros.getSelectedRow() != -1){
            filaSeleccionada = jTableLibros.getSelectedRow();
            
            txtCodigo.setText(jTableLibros.getValueAt(filaSeleccionada, 0) + "");
            txtIsbn.setText(jTableLibros.getValueAt(filaSeleccionada, 1) + "");
            txtTitulo.setText(jTableLibros.getValueAt(filaSeleccionada, 2) + "");
            txtAutor.setText(jTableLibros.getValueAt(filaSeleccionada, 3) + "");
            txtTema.setText(jTableLibros.getValueAt(filaSeleccionada, 4) + "");
            txtAnio.setText(jTableLibros.getValueAt(filaSeleccionada, 5) + "");
            txtIdioma.setText(jTableLibros.getValueAt(filaSeleccionada, 6) + "");
        }
    }//GEN-LAST:event_jTableLibrosMouseClicked

    private void txtBusquedaTituloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaTituloKeyPressed
        // TODO add your handling code here:
        if(!(txtBusquedaTitulo.getText().equals(""))){
            try {
                llenarJTableLibros(libroDAO.obtenerLibrosXTitulo(txtBusquedaTitulo.getText().trim()));
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }//GEN-LAST:event_txtBusquedaTituloKeyPressed

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
        // TODO add your handling code here:
        irAGUILibro();
    }//GEN-LAST:event_btnRegresarMouseClicked

    private void btnGenerarEjemplarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarEjemplarMouseClicked
        // TODO add your handling code here:
        try {
            if(txtTitulo.getText().equals("") || txtIsbn.getText().equals("") || txtAutor.getText().equals("")
                    || txtAnio.getText().equals("")){
                throw new ExcepcionPropia("Seleccionar un registro");
            }
            
            int idLibro = Integer.parseInt(txtCodigo.getText().trim());

            ejemplarDAO.agregarEjemplar(idLibro);
            
            JOptionPane.showMessageDialog(this, "Nuevo ejemplar registrado exitosamente.");
            irAGUILibro();
            
            establecerPorDefecto();
        } catch (ExcepcionPropia | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnGenerarEjemplarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarEjemplar;
    private javax.swing.ButtonGroup btnGrpOrdenamiento;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPaneEstudiante;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTableLibros;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtBusquedaTitulo;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtIdioma;
    private javax.swing.JTextField txtIsbn;
    private javax.swing.JTextField txtTema;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
