/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas.libro;

import vistas.estudiantes.*;
import DAOs.EstudianteDAO;
import DAOs.IdiomaDAO;
import DAOs.LibroDAO;
import DAOs.TemaDAO;
import entidades.Estudiante;
import entidades.Idioma;
import entidades.Libro;

import entidades.Tema;
import excepcionesPropias.ExcepcionPropia;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import listasPropias.ListaTemas;
import vistas.principal.GUIPrincipal;

/**
 *
 * @author Alexander
 */
public class GUIRegistroLibro extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUIAgregarNuevoEjemplar
     */
    
    LibroDAO libroDAO = new LibroDAO();
    TemaDAO temaDAO = new TemaDAO();
    IdiomaDAO idiomaDAO = new IdiomaDAO();
    ArrayList<Tema> listaTemas;
    ArrayList<Idioma> listaIdiomas;
    
    public GUIRegistroLibro() {
        initComponents();
        cargarCodigo();
        cargarCboBoxIdioma();
        cargarCboBoxTema();
    }

    private void limpiar(){
        lblCodigo.setText("");
        txtTitulo.setText("");
        txtIsbn.setText("");
        txtAutor.setText("");
        txtAnio.setText("");
        cboTema.setSelectedIndex(0);
        cboIdioma.setSelectedIndex(0);
    }
    
    private void establecerPorDefecto(){
        cargarCodigo();
        limpiar();
    }
    
    private void cargarCodigo(){
        try {
            lblCodigo.setText(libroDAO.generarNuevoCodigo()+ "");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Hubo un error al generar código");
        }
    }
    
    public void irAGUILibro(){
        GUIPrincipal.vacearDktpPane();
        
        GUILibro guiLibro = new GUILibro();
        GUIPrincipal.agregarJframe(guiLibro);
        guiLibro.setVisible(true);
    }
    
    private void cargarCboBoxTema(){
        
        try {
            listaTemas = temaDAO.obtenerTodosTemas();
            //materiaDAO.ordenarTemasXDescripcionASC(listaMaterias, 0, listaMaterias.size() - 1);
            
            for (int i = 0; i < listaTemas.size(); i++) {
                cboTema.addItem(listaTemas.get(i).getId()+ " - " + listaTemas.get(i).getDescripcion());
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
    
    private void cargarCboBoxIdioma(){
        
        try {
            listaIdiomas = idiomaDAO.obtenerIdiomas();
            //materiaDAO.ordenarTemasXDescripcionASC(listaMaterias, 0, listaMaterias.size() - 1);
            
            for (int i = 0; i < listaIdiomas.size(); i++) {
                cboIdioma.addItem(listaIdiomas.get(i).getIdidioma()+ " - " + listaIdiomas.get(i).getDescripcion());
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPaneEstudiante = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtIsbn = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtAutor = new javax.swing.JTextField();
        cboTema = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtAnio = new javax.swing.JTextField();
        cboIdioma = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(910, 530));

        jPaneEstudiante.setPreferredSize(new java.awt.Dimension(900, 530));
        jPaneEstudiante.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCodigo.setBackground(new java.awt.Color(204, 204, 204));
        lblCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCodigo.setOpaque(true);
        jPaneEstudiante.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 250, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Registro de libro");
        jPaneEstudiante.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 330, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Código:");
        jPaneEstudiante.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 80, -1));

        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
        });
        jPaneEstudiante.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 120, 50));

        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseClicked(evt);
            }
        });
        jPaneEstudiante.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 120, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Título:");
        jPaneEstudiante.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 90, -1));
        jPaneEstudiante.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 250, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("ISBN:");
        jPaneEstudiante.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 130, -1));
        jPaneEstudiante.add(txtIsbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 250, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Tema:");
        jPaneEstudiante.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 130, -1));
        jPaneEstudiante.add(txtAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 250, -1));

        jPaneEstudiante.add(cboTema, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 250, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Autor:");
        jPaneEstudiante.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 130, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Año de publicación:");
        jPaneEstudiante.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 130, -1));
        jPaneEstudiante.add(txtAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 250, -1));

        cboIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboIdiomaActionPerformed(evt);
            }
        });
        jPaneEstudiante.add(cboIdioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 250, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Idioma:");
        jPaneEstudiante.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 60, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, 898, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseClicked
        // TODO add your handling code here:
        try {
            if(txtTitulo.getText().equals("") || txtIsbn.getText().equals("") || txtAutor.getText().equals("")
                    || txtAnio.getText().equals("")){
                throw new ExcepcionPropia("Debe completar todos los campos");
            }
            
            Libro objLibro = new Libro();

            objLibro.setId(Integer.parseInt(lblCodigo.getText()));
            objLibro.setIsbn(txtIsbn.getText().trim());
            objLibro.setTitulo(txtTitulo.getText().trim());
            objLibro.setAutores(txtAutor.getText().trim());
            
            String detalle_tema[] = cboTema.getSelectedItem().toString().split(" - ");
            String detalle_idioma[] = cboIdioma.getSelectedItem().toString().split(" - ");
            
            objLibro.getTema().setId(Integer.parseInt(detalle_tema[0]));
            objLibro.getIdioma().setIdidioma(Integer.parseInt(detalle_idioma[0]));
            
            objLibro.setAniopublicacion(Integer.parseInt(txtAnio.getText().trim()));

            libroDAO.registrar(objLibro);
            
            JOptionPane.showMessageDialog(this, String.format("Nuevo libro %s registrado exitosamente", objLibro.getTitulo()));
            irAGUILibro();
            
            establecerPorDefecto();
        } catch (ExcepcionPropia | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnRegistrarMouseClicked

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
        // TODO add your handling code here:
        irAGUILibro();
    }//GEN-LAST:event_btnRegresarMouseClicked

    private void cboIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboIdiomaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboIdiomaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cboIdioma;
    private javax.swing.JComboBox<String> cboTema;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPaneEstudiante;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtIsbn;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
